# Embedded Tomcat Configuration 
server:
  port: 13050
  servlet:
    context-path: /
    session:
      timeout: 60m
    jsp:
      init-parameters:
         development: true
         
  connection-timeout: 50000
  tomcat:  
    uri-encoding: UTF-8
    accesslog:
      enabled: true
      pattern: "%h %l %u %t '%r' %s %b %D"
      rotate: true
      prefix: access
      suffix: .log
      file-date-format: .yyyy-MM-dd
      directory: ./media/log



login:
  admin: 
    success:
      url: "/home"
    default:
      url: "/user/rdt/adminLogin"    

    
anchorData:
  media:
    tiles: /WEB-INF/tiles/tiles.xml 
    upload-path: /nasa12345/files/
  verifyEmail : http://media.net/verifyEmail
  SGIS:
    public_key: 424e8922e78b4782975f
    service_id: 722d0be2bc834cf3b7ac
  chain:
    enabled: false
    strategy:
      fixed:
        auto: true            # Version strategy Number 생성 여부. true 이면 자동 생성
        version: "v00001"
    
resources:
  location:
    video : D:/RPA/
#    video : /usr/local/barun-webserver/academy/resource/video/
  uri:
    video : /user/lecture/resource/video/
    
scheduler:
  is:
    running: false    
    
access:
  denied:
    url: "/login"    
    
    
#Spring Default Configuration
spring:
  profiles:
    active: dev # 기본 환경 선택       

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://103.55.191.104:3306/job_navigator?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
   # jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/youth?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: anchor
    password: Anchoruser0914@
    hikari:
      max-lifetime: 1200000
      maximum-pool-size: 12
      minimum-idle: 5 
      idle-timeout: 30000  
      connection-test-query: SELECT 1  

  
  resources:
    chain:
      strategy:
        fixed:
          version: 
    cache:
      cachecontrol:
        max-age: 36000   

    
  application:
    name: com.anchordata.webframework
      
  messages:
    cache-duration: -1 
    basename: classpath:/config/message.properties
    encoding: UTF-8
   
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
      
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp 

  cache:
    ehcache:
      config: classpath:/config.ehcache.xml
    
  devtools:
    livereload:
      enabled: true    


  google:
    client:
      clientId: 744744614208-obapm74n0kn9ug54len0a838am3ct75l.apps.googleusercontent.com
      clientSecret: KYaQUpkFq_u-jNNBZ1Ju_1KE
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email, profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    recaptcha:
      siteKey: 6LdGVgEVAAAAAJz8oWKmIs5kHyp5qwCRQo5-XYEA
      secretKey: 6LdGVgEVAAAAAKgzxwUdumjFDsvk2jASX1ieBp3X
    
    
--- # dev 환경
spring:
  profiles: dev
  
#  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: jdbc:log4jdbc:mysql://139.150.76.4:3306/sun_job_navigator?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
#    username: ketep
#    password: Ketepdbuser0504!@
#    hikari:
#      max-lifetime: 1200000
#      maximum-pool-size: 12
#      minimum-idle: 5 
#      idle-timeout: 30000  
#      connection-test-query: SELECT 1  
  
server:
  port: 11011

tomcat:
  ajp:
    protocol: "AJP/1.3"
    port: 13011
    enabled: true 
    
etc:
  login:
    kakao_redirection_url: http://localhost:11001/login/kakao
    kakao_faq_redirection_url: http://localhost:11001/login/kakao/faq
    kakao_policy_redirection_url: http://localhost:11001/login/kakao/policy
    kakao_actShare_redirection_url: http://localhost:11001/login/kakao/actShare    


# 운영 환경
---
spring:
  profiles: prod
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/job_navigator?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: ketep
    password: Ketepdbuser0504!@
    hikari:
      max-lifetime: 1200000
      maximum-pool-size: 12
      minimum-idle: 5 
      idle-timeout: 30000  
      connection-test-query: SELECT 1 
  
server:
  port: 11021
  
tomcat:
  ajp:
    protocol: "AJP/1.3"
    port: 13021
    enabled: true  
    
etc:
  login:
    kakao_redirection_url: http://youthstart.or.kr/login/kakao
    kakao_faq_redirection_url: http://youthstart.or.kr/login/kakao/faq
    kakao_policy_redirection_url: http://youthstart.or.kr/login/kakao/policy
    kakao_actShare_redirection_url: http://youthstart.or.kr/login/kakao/actShare
  
  
# 운영 테스트 환경
---
spring:
  profiles: prod_test
  
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/job_navigator?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    username: ketep
    password: Ketepdbuser0504!@
    hikari:
      max-lifetime: 1200000
      maximum-pool-size: 12
      minimum-idle: 5 
      idle-timeout: 30000  
      connection-test-query: SELECT 1 
  
server:
  port: 11031

  
tomcat:
  ajp:
    protocol: "AJP/1.3"
    port: 13031
    enabled: true  
  
etc:
  login:
    kakao_redirection_url: http://youthstart.or.kr/login/kakao
    kakao_faq_redirection_url: http://youthstart.or.kr/login/kakao/faq
    kakao_policy_redirection_url: http://youthstart.or.kr/login/kakao/policy
    kakao_actShare_redirection_url: http://youthstart.or.kr/login/kakao/actShare
  